### ISSUE TITLE
Missing days report doesn't use JIRA configured working hours per day

### ISSUE THREAD

**Issue by BobVul** [everit-org/jira-timetracker-plugin#133]
The option "Check the worklog spent time is equal or greater to 8 hours." in Missing Days Report seems to use a hardcoded 8 hours: https://github.com/everit-org/jira-timetracker-plugin/blob/v2.x/src/main/java/org/everit/jira/timetracker/plugin/JiraTimetrackerPluginImpl.java#L788

However, JIRA Time Tracking allows you to configure working hours per day: https://confluence.atlassian.com/jira/configuring-time-tracking-185729592.html

We use 7.5 hours. This makes that option useless for us, as it's using the wrong number of hours.

Could you take the JIRA setting for hours? Or at least make it configurable in some other way?

**Comment by bordatesz** [comment]
Thank you for the notification. This fix will be part of the next release.

In the future, we plan to add a new feature where working hours per day can be set individually for each user, if it differs from the global configuration. (e.g. for a trainee) Would you find this feature helpful?

**Comment by BobVul** [comment]
Thanks!

Per-user working hours sounds like it could be useful (we do not currently have anyone on different hours, though that might change). Just having the global option would be a large improvement already.

**Comment by BobVul** [comment]
In fact, it seems like the rest of the plugin also uses a hardcoded 8 hours per day. For example: https://github.com/everit-org/jira-timetracker-plugin/blob/31155350da213ac96665c2511349ddfd2c5f1a93/src/test/java/org/everit/jira/timetracker/plugin/DurationBuilder.java#L27

This is apparent if we try to use the Table Report. For example, if we have 7.5 hours per working day in the JIRA global settings and 4d added to a work log, the Timetracker plugin lists it as 3d 6h. Unfortunately, this makes the table report difficult to use without further processing to correct the durations.

Should I create a separate issue?

**Comment by bordatesz** [comment]
It's not necessary. We recognized these too, so I made issues in our JIRA system to eliminate all of these hardcoded values and use the global settings instead. I will notify you here if we finished with it. Please, keep an eye on it!

**Comment by bordatesz** [comment]
Hi there!
This issue is fixed in version 2.3.0, which is available on the marketplace: https://marketplace.atlassian.com/plugins/org.everit.jira.timetracker.plugin/server/overview

**Comment by BobVul** [comment]
Thanks for the update, @bordatesz 

There seems to be a bug: we have Time Tracking configured to 7.5 working hours per day, but the Timetracker plugin table shows what seems to be 7 hours per day. On a day with 7.5 hours of work logs entered, it says "Day     (1d 0h 30m) ". With 7 hours entered, it says " Day  (1d 0h 0m)".

Unfortunately, I am unable to test different working hours as this is a production JIRA system. I'd guess it's ignoring the fractional part (0.5) of the configured working hours.

**Comment by BobVul** [comment]
For reference, here are our current Time Tracking settings:

> The number of working hours per day is **7.5**.
> The number of working days per week is **5**.
> Time estimates will be displayed in the following format: **pretty (e.g. 4 days, 6 hours, 30 minutes)**
> The current default unit for time tracking is **minute**.
> Copying of comments to work description is currently **enabled**.

**Comment by bordatesz** [comment]
You are right. There is a bug with fractional numbers.
We are working on it, and i hope we can release a bugfix in a few days. (maybe today)

**Comment by bordatesz** [comment]
Hi @Elusive138! 
We are ready, and it's fixed in version 2.3.1
Please let me know whether it is working properly!

**Comment by BobVul** [comment]
Seems to work well. Thanks!

**Comment by BobVul** [comment]
@bordatesz While the number of days is correctly counted in the Table Report now, it looks like the Missing Days Report is still incorrect:
1. Set working hours per day to 7.5 (7h 30m)
2. Fill in 7h for one day
3. Run Missing Days Report with "Check the worklog spent time is equal or greater to the time is expected a day."

The 7h day (30m missing) does not show up. Looks like the Missing Days Report is still ignoring the fractional part.

**Comment by bordatesz** [comment]
Sorry, we overlooked it, but it will be fixed soon. We are not planning a release in the next few days. Can you clone/download Timetracker and build it for yourself?

**Comment by BobVul** [comment]
Seems to work in 2.3.2-SNAPSHOT.

Thanks!

**Comment by bordatesz** [comment]
Yes, the snapshot contains the fix. Your welcome!
